### ISSUE TITLE
HOME_SLIDER_BANNER_GROUP not defined

### ISSUE THREAD

**Issue by dbltoe** [lat9/bs4_home_slider#2]
installed on 1.5.7d with Bootstrap 3.3.0
All the files are in the boostrap folder and its clone, metalBoot
The developer's Tool Kit shows it used in a Where statement in both the ttpl_index_slider.php files.
I have searched the DB and it is not mentioned in the banners table.
I have not found any documentation mentioning it either.
As usual I am probably missing something obvious, but we are getting:
****************************************
[27-Apr-2022 19:07:32 UTC] Request URI: /index.php?main_page=index&cPath=11%27nvOpzp;%20AND%201=1%20OR%20(%3C%27%22%3EiKO)),, IP address: 108.31.158.71
#1 include(/includes/templates/metalBoot/templates/tpl_index_slider.php) called at [/includes/templates/metalBoot/templates/tpl_index_default.php:33]
#2 require(/includes/templates/metalBoot/templates/tpl_index_default.php) called at [/includes/modules/pages/index/main_template_vars.php:232]
#3 require(/includes/modules/pages/index/main_template_vars.php) called at [/includes/templates/metalBoot/common/tpl_main_page.php:202]
#4 require(/includes/templates/metalBoot/common/tpl_main_page.php) called at [/index.php:94]
--> PHP Warning: Use of undefined constant HOME_SLIDER_BANNER_GROUP - assumed 'HOME_SLIDER_BANNER_GROUP' (this will throw an Error in a future version of PHP) in /includes/templates/metalBoot/templates/tpl_index_slider.php on line 13.

**Comment by lat9** [comment]
Yes, that should be BS4_SLIDER_BANNER_GROUP, sigh.
